version: "3.5"
networks:
  dev-net:
   external:
     name: ${DOCKER_NETWORK_NAME}
services:
  client: 
    container_name: ${CONTAINER_NAME}
    environment:
      - LOW
      - HIGH
      - SOCKET_URL
      - PORT
      - MODE
      - DEV_MODE_FILENAME
    working_dir : /${WORKING_DIR}
    image: "node:10"
    volumes: 
      - .:/${VOLUMES}
    command: bash -c "npm run dev"
    ports:
      - ${PORT}:${PORT}
    networks:
      - ${DOCKER_NETWORK}
      