version: "3"
services:
  api:
    container_name: "api"
    build: .
    ports:
      - 3000:3000
    command: bash -c "npm start"
    depends_on:
      - database

  
  database:
    container_name: "mongoDB"
    image: mongo
    restart: always
    ports:
      - 27019:27019